### ISSUE TITLE
ms-trigger-ico without background image

### ISSUE THREAD

**Issue by meghuizen** [Magicsuggest/magicsuggest#27]
The ms-trigger-ico now uses a background-image, with data:image/png. Why not using the same principel als bootstrap it's **.caret** option?

For example, replace the **.ms-ctn .ms-trigger .ms-trigger-ico** code in the CSS with the following:

``` CSS
.ms-ctn .ms-trigger .ms-trigger-ico {
    display: inline-block;
    width: 0;
    height: 0;
    vertical-align: top;
    border-top: 4px solid gray;
    border-right: 4px solid transparent;
    border-left: 4px solid transparent;
    content: "";
    margin-left: 9px;
    margin-top: 13px;
}
```
